server:
  port: 8080

github:
  apiBaseUrl: https://api.github.com
  token: ${GITHUB_TOKEN:}
  retry:
    maxAttempts: 3
    initialBackoffMillis: 250
    maxBackoffMillis: 2000

spring:
  main:
    banner-mode: "off"

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic
